blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/RichardSlater/bromcom-timetable-formatter/discussions
    about: Please use Discussions for general questions or brainstorming.
