[package]
name = "timetable_core"
version = "0.1.0"
edition = "2021"

[dependencies]
lopdf = "0.38"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
svg = "0.18"
roxmltree = "0.21"
thiserror = "2.0"
regex = "1.11"
chrono = "0.4"
